### ISSUE TITLE
Low-level interface for Bytes and Bigarray?

### ISSUE THREAD

**Issue by favonia** [ygrek/ocaml-snappy#2]
The snappy compression aims at high throughput, and thus a lower-level interface that avoids copying could be handy. (`BigArray` is relevant because its layout is identical to C arrays.)

**Comment by ygrek** [comment]
Patches welcome, it should be pretty straightforward to add

**Comment by favonia** [comment]
I see. Thanks. I decided not to use the snappy compression, so I may not plan a PR soon.
